import { ShortFilm, Director, Hero, Comment } from '../types/shortfilm';

export const INITIAL_DIRECTORS: Director[] = [
  {
    id: 'dir-1',
    name: 'Aarav Sharma',
    bio: '24-year-old indie filmmaker known for psychological thrillers and cinematic lighting. Winner of National Short Film Fest 2025.',
    profile_pic_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
    avg_rating: 4.9,
    film_count: 5,
    follower_count: 14200,
  },
  {
    id: 'dir-2',
    name: 'Rohan Varma',
    bio: 'Passionate visual storyteller crafting emotionally rich romantic dramas & uplifting coming-of-age shorts.',
    profile_pic_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
    avg_rating: 4.8,
    film_count: 4,
    follower_count: 11800,
  },
  {
    id: 'dir-3',
    name: 'Ananya Roy',
    bio: 'Experimental director blending high-concept comedy with surrealist visuals. Graduate of FTII Pune.',
    profile_pic_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=500&q=80',
    avg_rating: 4.7,
    film_count: 6,
    follower_count: 9500,
  },
  {
    id: 'dir-4',
    name: 'Karan Mehta',
    bio: 'Cyberpunk & dark neo-noir enthusiast. Directing fast-paced suspense thrillers under 3 minutes.',
    profile_pic_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
    avg_rating: 4.6,
    film_count: 3,
    follower_count: 7300,
  },
  {
    id: 'dir-5',
    name: 'Priya Sundaram',
    bio: 'Documentary and slice-of-life short filmmaker capturing raw human emotions in 60-second micro-stories.',
    profile_pic_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=500&q=80',
    avg_rating: 4.5,
    film_count: 4,
    follower_count: 6100,
  },
];

export const INITIAL_HEROES: Hero[] = [
  {
    id: 'hero-1',
    name: 'Kabir Das',
    bio: 'Method actor starring in intense action and thriller short films. Featured in 8 award-winning shorts.',
    profile_pic_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
    film_count: 8,
  },
  {
    id: 'hero-2',
    name: 'Tara Malhotra',
    bio: 'Theater performer and breakout actress in romantic & uplifting indie cinema.',
    profile_pic_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=500&q=80',
    film_count: 6,
  },
  {
    id: 'hero-3',
    name: 'Siddharth Rao',
    bio: 'Versatile character actor with a penchant for high-energy comedy and dark mystery.',
    profile_pic_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=500&q=80',
    film_count: 5,
  },
];

export const INITIAL_FILMS: ShortFilm[] = [
  {
    id: 'film-1',
    title: 'The Silent Echo',
    director_id: 'dir-1',
    director_name: 'Aarav Sharma',
    director_pic: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
    hero_ids: ['hero-1', 'hero-2'],
    hero_names: ['Kabir Das', 'Tara Malhotra'],
    duration_sec: 165,
    mood_tag: 'thriller',
    drive_file_id: '1Bzi-KXJ_05sX1J5T_SampleDriveId1',
    drive_link: 'https://drive.google.com/file/d/1Bzi-KXJ_05sX1J5T_SampleDriveId1/preview',
    youtube_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    youtube_id: 'dQw4w9WgXcQ',
    video_source: 'youtube',
    video_fallback_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnail_url: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    overview: 'A lone detective discovers an encrypted audio frequency transmitted from an abandoned subway station that predicts events 3 minutes in the future.',
    rating_avg: 4.9,
    rating_count: 128,
    status: 'approved',
    upload_date: '2026-07-25',
    views_count: 24500,
    likes_count: 3890,
  },
  {
    id: 'film-2',
    title: 'Sunrise at 4 AM',
    director_id: 'dir-2',
    director_name: 'Rohan Varma',
    director_pic: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=80',
    hero_ids: ['hero-2'],
    hero_names: ['Tara Malhotra'],
    duration_sec: 110,
    mood_tag: 'uplifting',
    drive_file_id: '1Azi-KXJ_05sX2J5T_SampleDriveId2',
    drive_link: 'https://drive.google.com/file/d/1Azi-KXJ_05sX2J5T_SampleDriveId2/preview',
    youtube_url: 'https://www.youtube.com/watch?v=L_LUpnjgPso',
    youtube_id: 'L_LUpnjgPso',
    video_source: 'youtube',
    video_fallback_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnail_url: 'https://img.youtube.com/vi/L_LUpnjgPso/hqdefault.jpg',
    overview: 'Two strangers meet on a fog-covered rooftop in Mumbai right before dawn, sharing a thermos of hot tea.',
    rating_avg: 4.8,
    rating_count: 94,
    status: 'approved',
    upload_date: '2026-07-28',
    views_count: 18200,
    likes_count: 2910,
  },
  {
    id: 'film-3',
    title: 'Midnight Coffee Breakdown',
    director_id: 'dir-3',
    director_name: 'Ananya Roy',
    director_pic: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=500&q=80',
    hero_ids: ['hero-3'],
    hero_names: ['Siddharth Rao'],
    duration_sec: 52,
    mood_tag: 'comedy',
    drive_file_id: '1Czi-KXJ_05sX3J5T_SampleDriveId3',
    drive_link: 'https://drive.google.com/file/d/1Czi-KXJ_05sX3J5T_SampleDriveId3/preview',
    youtube_url: 'https://www.youtube.com/watch?v=aqz-KE-bpKQ',
    youtube_id: 'aqz-KE-bpKQ',
    video_source: 'youtube',
    video_fallback_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnail_url: 'https://img.youtube.com/vi/aqz-KE-bpKQ/hqdefault.jpg',
    overview: 'When the office coffee machine gains artificial intelligence, an overworked developer tries to negotiate an espresso.',
    rating_avg: 4.7,
    rating_count: 110,
    status: 'approved',
    upload_date: '2026-07-20',
    views_count: 31000,
    likes_count: 4200,
  },
  {
    id: 'film-4',
    title: 'Shadows in the Rain',
    director_id: 'dir-4',
    director_name: 'Karan Mehta',
    director_pic: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
    hero_ids: ['hero-1'],
    hero_names: ['Kabir Das'],
    duration_sec: 240,
    mood_tag: 'dark',
    drive_file_id: '1Dzi-KXJ_05sX4J5T_SampleDriveId4',
    drive_link: 'https://drive.google.com/file/d/1Dzi-KXJ_05sX4J5T_SampleDriveId4/preview',
    youtube_url: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    youtube_id: 'jNQXAC9IVRw',
    video_source: 'youtube',
    video_fallback_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnail_url: 'https://img.youtube.com/vi/jNQXAC9IVRw/hqdefault.jpg',
    overview: 'In a neon-drenched alleyway, an informant has 4 minutes to hand over a cipher.',
    rating_avg: 4.6,
    rating_count: 85,
    status: 'approved',
    upload_date: '2026-07-22',
    views_count: 14300,
    likes_count: 1980,
  },

  // PENDING Films for Admin Review Queue Testing
  {
    id: 'film-pending-1',
    title: 'Neon Horizon: Protocol 7',
    director_id: 'dir-4',
    director_name: 'Karan Mehta',
    director_pic: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80',
    hero_ids: ['hero-1'],
    hero_names: ['Kabir Das'],
    duration_sec: 175,
    mood_tag: 'thriller',
    drive_file_id: '1Gzi-KXJ_05sX7J5T_PendingDriveId1',
    drive_link: 'https://drive.google.com/file/d/1Gzi-KXJ_05sX7J5T_PendingDriveId1/preview',
    video_fallback_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=800&q=80',
    overview: 'A futuristic cyber hacker breaches an orbital satellite control center in 2 minutes before security deploys.',
    rating_avg: 0,
    rating_count: 0,
    status: 'pending',
    upload_date: '2026-07-30',
    views_count: 0,
    likes_count: 0,
  },
  {
    id: 'film-pending-2',
    title: 'Whispers of Monsoon',
    director_id: 'dir-5',
    director_name: 'Priya Sundaram',
    director_pic: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=500&q=80',
    hero_ids: ['hero-2'],
    hero_names: ['Tara Malhotra'],
    duration_sec: 140,
    mood_tag: 'romantic',
    drive_file_id: '1Hzi-KXJ_05sX8J5T_PendingDriveId2',
    drive_link: 'https://drive.google.com/file/d/1Hzi-KXJ_05sX8J5T_PendingDriveId2/preview',
    video_fallback_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutback2013.mp4',
    thumbnail_url: 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?auto=format&fit=crop&w=800&q=80',
    overview: 'An artist paints portraits of strangers waiting under a bus stop umbrella in heavy rain.',
    rating_avg: 0,
    rating_count: 0,
    status: 'pending',
    upload_date: '2026-07-30',
    views_count: 0,
    likes_count: 0,
  },
];

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: 'comm-1',
    film_id: 'film-1',
    user_id: 'dir-1',
    user_name: 'Aarav Sharma',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80',
    user_role: 'director',
    is_verified: true,
    text: 'Shot this entire short in 6 hours using natural subway lighting and anamorphic lenses.',
    timestamp: '2 hours ago',
    is_flagged: false,
  },
  {
    id: 'comm-2',
    film_id: 'film-1',
    user_id: 'hero-1',
    user_name: 'Kabir Das',
    user_avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80',
    user_role: 'hero',
    is_verified: true,
    text: 'Aarav’s direction was intense and super precise! The subway twist was pure genius.',
    timestamp: '1 hour ago',
    is_flagged: false,
  },
  {
    id: 'comm-3',
    film_id: 'film-2',
    user_id: 'user-spammer',
    user_name: 'Random Bot User',
    user_avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=300&q=80',
    user_role: 'viewer',
    is_verified: false,
    text: 'Spam link test message buy crypto coins fast!!!',
    timestamp: '30 mins ago',
    is_flagged: true,
  },
];
